app: gcb
region: us-east-1
solution_stack_name: 64bit Amazon Linux 2016.03 v2.1.6 running Ruby 2.3 (Passenger Standalone)
strategy: inplace-update 
keep_latest: 10
development:
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.micro

production:
  strategy: blue-green 
  options:
    aws:autoscaling:launchconfiguration:
      InstanceType: t1.small

